### ISSUE TITLE
Feature request - autoclean on interval

### ISSUE THREAD

**Issue by TwilightMercy** [peno64/repository.peno64#1]
It is possible for you to add options to AutoCleanup, not only on Start?
Like daily/weekly/etc

example for that feature is in OpenWizard addon

thanks!

**Comment by peno64** [comment]
Looks a good idea. Can you put this request in https://github.com/peno64/script.ezmaintenanceplus/issues and remove it here?

**Comment by peno64** [comment]
See https://github.com/peno64/script.ezmaintenanceplus/issues/3
